
open_manipulator:

  # joint_state_controller:
  #   type: joint_state_controller/JointStateController
  #   publish_rate: 1000


  # joint1_position:
  #   type: position_controllers/JointPositionController
  #   joint: joint1

  # joint2_position:
  #   type: position_controllers/JointPositionController
  #   joint: joint2

  # joint3_position:
  #   type: position_controllers/JointPositionController
  #   joint: joint3

  # joint4_position:
  #   type: position_controllers/JointPositionController
  #   joint: joint4

  # gripper_position:
  #   type: effort_controllers/JointPositionController
  #   joint: gripper
  #   pid: {p: 100, i: 0, d: 0}
    
  # gripper_sub_position:
  #   type: effort_controllers/JointPositionController
  #   joint: gripper_sub
  #   pid: {p: 100, i: 0, d: 0}



  # Arm controller configuration.
  group_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4


  group_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - gripper
      - gripper_sub
    gains:
      gripper:  {p: 5000.0, i: 0.0, d: 10}
      gripper_sub:  {p: 5000.0, i: 0.0, d: 10}


  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

