
  controller_manager_ns: ''
  controller_list:
    - name: open_manipulator/group_arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
    - name: open_manipulator/group_gripper_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - gripper
        - gripper_sub
